a=input()
b=input()
c=float(a)
d=float(b)
x1,y1=map(int,a.split("."))
x2,y2=map(int,b.split("."))
if(c<d):
    if((x1,y1)<(x2,y2)):
        print(d)
    else:
        print(-1)
elif(c>d):
    if((x1,y1)>(x2,y2)):
        print(c)
    else:
        print(-1)
else:
    print(c)